import type { Metadata } from "next";
import "./globals.css";
import { Halfre } from "@/fonts";
import ScrollProvider from "@/provider/ScrollProvider";
import Navbar from "@/components/Reuseable/navbar";
import Footer from "@/components/Reuseable/Footer2";

export const metadata: Metadata = {
  title: "STR Atman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Halfre.variable}  antialiased`}>
        <Navbar />
        <ScrollProvider>{children}</ScrollProvider>
        <Footer />
      </body>
    </html>
  );
}
