import type { Metadata } from "next";
import "./globals.css";
import { Halfre } from "@/fonts";
import LayoutProvider from "@/layout/LayoutProvider";

export const metadata: Metadata = {
  title: "STR Atman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Halfre.variable}  antialiased`}>
        <LayoutProvider>
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
