import type { Metadata } from "next";
import "./globals.css";
import { Halfre, Velcan } from "@/fonts";
import LayoutProvider from "@/layout/LayoutProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "STR Atman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Halfre.variable} ${Velcan.variable} antialiased `}>
        <Toaster position="top-right" />
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
