// Utility functions for Instagram integration

export interface InstagramPost {
  id: number;
  image: string;
  alt: string;
  hasOverlay: boolean;
  caption: string;
  likes: string;
  postUrl: string;
  embedUrl: string;
}

/**
 * Convert Instagram post URL to embed URL
 * Example: https://www.instagram.com/p/DQ1YlwOkSNJ/ -> https://www.instagram.com/p/DQ1YlwOkSNJ/embed
 */
export const getInstagramEmbedUrl = (postUrl: string): string => {
  // Remove trailing slash if present
  const cleanUrl = postUrl.replace(/\/$/, '');
  return `${cleanUrl}/embed`;
};

/**
 * Extract post ID from Instagram URL
 * Example: https://www.instagram.com/p/DQ1YlwOkSNJ/ -> DQ1YlwOkSNJ
 */
export const extractInstagramPostId = (postUrl: string): string => {
  const match = postUrl.match(/\/p\/([A-Za-z0-9_-]+)/);
  return match ? match[1] : '';
};

/**
 * Generate Instagram embed HTML
 * This can be used if you want to embed Instagram posts directly
 */
export const generateInstagramEmbedHtml = (postUrl: string): string => {
  const postId = extractInstagramPostId(postUrl);
  return `
    <blockquote class="instagram-media" 
      data-instgrm-captioned 
      data-instgrm-permalink="${postUrl}?utm_source=ig_embed&utm_campaign=loading" 
      data-instgrm-version="14">
      <div style="padding:16px;">
        <a href="${postUrl}?utm_source=ig_embed&utm_campaign=loading" 
           style="background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" 
           target="_blank">
          <div style="display: flex; flex-direction: row; align-items: center;">
            <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div>
            <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;">
              <div style="background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div>
              <div style="background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div>
            </div>
          </div>
          <div style="padding: 19% 0;"></div>
          <div style="display:block; height:50px; margin:0 auto 12px; width:50px;">
            <!-- Instagram icon SVG -->
          </div>
          <div style="padding-top: 8px;">
            <div style="color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">
              View this post on Instagram
            </div>
          </div>
        </a>
        <p style="color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">
          <a href="${postUrl}?utm_source=ig_embed&utm_campaign=loading" 
             style="color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" 
             target="_blank">
            A post shared by Silambarasan TR (@silambarasantrofficial)
          </a>
        </p>
      </div>
    </blockquote>
  `;
};

/**
 * Sample Instagram posts data
 * Update these URLs with the latest posts from @silambarasantrofficial
 */
export const sampleInstagramPosts: InstagramPost[] = [
  {
    id: 1,
    image: "/simbusong1.jpg",
    alt: "STR Instagram Post 1",
    hasOverlay: true,
    caption: "Latest update from STR",
    likes: "125K",
    postUrl: "https://www.instagram.com/p/DQ1YlwOkSNJ/",
    embedUrl: "https://www.instagram.com/p/DQ1YlwOkSNJ/embed"
  },
  // Add more posts here...
];

/**
 * Instructions for updating Instagram posts:
 * 
 * 1. Go to https://www.instagram.com/silambarasantrofficial/
 * 2. Click on a post to open it
 * 3. Copy the URL from the browser (e.g., https://www.instagram.com/p/DQ1YlwOkSNJ/)
 * 4. Update the postUrl in the instagramPosts array
 * 5. The embedUrl will be automatically generated by adding '/embed' to the postUrl
 * 6. Update the caption, likes, and image path as needed
 * 
 * For getting the image:
 * - You can screenshot the post or use the thumbnail
 * - Save it in the public folder
 * - Update the image path in the post data
 */